### ISSUE TITLE
Apple Silicon version not updated in quickstart

### ISSUE THREAD

**Issue by jpwgnr** [cvmfs/doc-cvmfs#237]
This line is out of date I think:
https://github.com/cvmfs/doc-cvmfs/blob/0f62daf15e2805f626869efbf34b425399cc8b6e/cpt-quickstart.rst?plain=1#L121

Not sure whether you still need this for any new apple machine or if you can also install it by now with the "normal" image.

**Comment by vvolkl** [comment]
Yes, thanks for raising that. I've built new .pkg files for the new 2.12 release, and have added them to the docs. By the way, we now also have packages that make use of Fuse-t, that can be installed with homebrew:
```
          brew tap macos-fuse-t/cask
          brew tap cvmfs/homebrew-cvmfs
          brew install cvmfs
```
I'll add that to the docs too.

**Comment by jpwgnr** [comment]
thank you!
